version: '3.7'

services:
  # Servicio para PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - ${APP_NETWORK}
    depends_on:
      - db
    expose:
      - "9000"
  
  # Servicio para Nginx
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - ${APP_NETWORK}
    depends_on:
      - app
  
  # Servicio para MySQL
  db:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ${APP_NETWORK}

# Definimos la red de la aplicación
networks:
  ${APP_NETWORK}:
    driver: bridge

# Volumen para almacenar los datos de MySQL
volumes:
  db-data:
